### ISSUE TITLE
[Feature] Show Map First on Mobile browsers 

### ISSUE THREAD

**Issue by arky** [geohacker/bangmandu#1]
Perhaps it is a good idea to show the map first in mobile views. As this is a expedition live map people would like a see the map first instead of bunch of text. 

![screenshot from 2017-08-31 00-38-49](https://user-images.githubusercontent.com/808895/29886717-4cc62840-8de5-11e7-9e33-ee61623d4c59.png)

**Comment by arky** [comment]
The Flight of the Swans expedition mobile page is good example of this kind of minimal UI. 

![flight-of-swans](https://user-images.githubusercontent.com/808895/29887113-9530e7f4-8de6-11e7-8d58-13148e5e7b60.png)
 
https://www.flightoftheswans.org/expedition-map/

**Comment by geohacker** [comment]
@arky thank you for the ticket! I did consider having the map on top but it lost the context of the trip but I can give it another shot.

**Comment by arky** [comment]
@geohacker I think you can quickly give the background of the project with something like the title and a caption ... 

"Follow our mapping journey across India to the foothills of Himalayas" 

And follow it by inviting the audience to engage via the maps and social media channels.

**Comment by arky** [comment]
@geohacker  On second thoughts. Perhaps just hiding few elements greatly enhances user experience on mobile devices.  

See @geohacker/bangmandu#2

**Comment by geohacker** [comment]
Going to work on a bit of rewrite when I have time next. Thank you for the suggestions @arky!
