### ISSUE TITLE
Map zooms out when mouse moves out of a link

### ISSUE THREAD

**Issue by answerquest** [geohacker/bangmandu#3]
Why the fancy zooming in if you're only going to zoom it back out when I try to browse the map. Might not make much difference for the road trip but I have other applications in mind where this could be applied.

**Comment by arky** [comment]
@geohacker I agree with @answerquest . The mouseover[1] and mouseleave[2] zoom and recenter feature affect usability of the map.   

[1] https://github.com/geohacker/bangmandu/blob/gh-pages/js/app.js#L111
[2] https://github.com/geohacker/bangmandu/blob/gh-pages/js/app.js#L119

**Comment by geohacker** [comment]
Of course - I think this was just residual while I was playing around with possible interactions.
